// <auto-generated />
namespace BasinTakip.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class editeventCalendareventSpecial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editeventCalendareventSpecial));
        
        string IMigrationMetadata.Id
        {
            get { return "201705181450483_editeventCalendar-eventSpecial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
